spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 575730622
    url: jdbc:mysql://127.0.0.1:3306/weixinorderDB?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env: dev
